---
- name: Check if TAR is Present
  ansible.builtin.package:
    name: tar
    state: present
  when: monitoring_tool is defined and monitoring_tool == "node_exporter"

- name: Binary Node Exporter
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v1.8.1/node_exporter-1.8.1.linux-amd64.tar.gz"
    dest: /tmp/node_exporter.tar.gz
    mode: '0644'
  when: monitoring_tool is defined and monitoring_tool == "node_exporter"

- name: Node Exporter Exporting
  ansible.builtin.unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /usr/local/bin/
    remote_src: yes
    extra_opts: [--strip-components=1]
  when: monitoring_tool is defined and monitoring_tool == "node_exporter"

- name: Check if node_expoter is running
  ansible.builtin.file:
    path: /usr/local/bin/node_exporter
    mode: '0755'
    owner: root
    group: "{{ 'nogroup' if ansible_os_family == 'Debian' else 'nobody' }}"
  when: monitoring_tool is defined and monitoring_tool == "node_exporter"

- name: Node Exporter SYSTEMD
  ansible.builtin.copy:
    dest: /etc/systemd/system/node_exporter.service
    content: |
      [Unit]
      Description=Prometheus Node Exporter
      After=network.target

      [Service]
      ExecStart=/usr/local/bin/node_exporter
      User=nobody
      Group={{ 'nogroup' if ansible_os_family == 'Debian' else 'nobody' }}

      [Install]
      WantedBy=multi-user.target
  when: monitoring_tool is defined and monitoring_tool == "node_exporter"

- name: Refresh SYSTEMD to pick node_exporter 
  ansible.builtin.systemd:
    daemon_reload: yes
  when: monitoring_tool is defined and monitoring_tool == "node_exporter"

- name: Start & Enable Node Exporter
  ansible.builtin.systemd:
    name: node_exporter
    state: started
    enabled: yes
  when: monitoring_tool is defined and monitoring_tool == "node_exporter"

