---
  - name: Install Apache Web Server
    ansible.builtin.package:
      name: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"
      state: present

  - name: Start & Enable Apache
    ansible.builtin.service:
      name: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"
      state: started
      enabled: yes
